14:03:02.05 [INFO] Completed: Building requirements.pex
14:03:10.07 [INFO] Completed: Building pytest.pex with 3 requirements: pytest-cov>=2.10.1,<2.11, pytest>=6.0.1,<6.3, zipp==2.1.0
14:03:12.33 [31m[WARN][0m Completed: test - test/foobar/foobar_test.py failed (exit code 2).
[1m============================= test session starts ==============================[0m
platform darwin -- Python 3.7.9, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /private/var/folders/1_/j6pgbhz546g4t92sckw7215c0000gn/T/process-executionyvBBcY
plugins: cov-2.10.1
collected 0 items / 1 error

==================================== ERRORS ====================================
[31m[1m_________________ ERROR collecting test/foobar/foobar_test.py __________________[0m
[31mImportError while importing test module '/private/var/folders/1_/j6pgbhz546g4t92sckw7215c0000gn/T/process-executionyvBBcY/test/foobar/foobar_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/Users/jyggen/.pyenv/versions/3.7.9/lib/python3.7/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
test/foobar/foobar_test.py:1: in <module>
    from foobar.foobar import foobar
E   ModuleNotFoundError: No module named 'foobar.foobar'[0m
=========================== short test summary info ============================
ERROR test/foobar/foobar_test.py
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
[31m=============================== [31m[1m1 error[0m[31m in 0.16s[0m[31m ===============================[0m


